import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextAuthProvider from "@/lib/auth/Provider";
import TrpcProvider from "@/lib/trpc/Provider";
import { Toaster } from "@/components/ui/toaster";
import {SidebarNav} from '@/components/Navbar';
import { PlusCircle } from 'lucide-react';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
<NextAuthProvider>
<TrpcProvider>
  <div className="flex">
  <SidebarNav items={[{
    title:"Home",
    href:"/",
  },{
    title:"Availablity",
    href:"/availablity",
  },{
    title:"eventtypes",
    href:"/eventtypes"
  },{
    title:"Bookings",
    href:"/bookings"
  }]}/>
  {children}
  </div>
<Toaster />
</TrpcProvider>
</NextAuthProvider>
</body>
    </html>
  )
}
